#!/bin/bash
find . -regex '.*\.\(c\|h\)' -not -path "./build/*" -not -path "./external/*" -exec echo {} \; -exec clang-format -style=file -i {} \;
#find src/ -name '*.cpp' -o -name '*.hpp' -o -name '*.c' -o -name '*.h' | xargs clang-format-13 -i

